baseURL = "https://robindolle.be/"
title = "Robin Dollé"

languageCode = "nl-be"
DefaultContentLanguage = "nl"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

disableRSS = true
disableSitemap = true
disable404 = true

GoogleAnalytics = "UA-60601159-1"

[params.author]
  name = "Robin Dollé"

[params]
  # Metadata mostly used in document's head
  description = "Homepage and blog by Robin Dollé"
  keywords = "homepage, blog, informatics, development, programming"
  images = [""]

  # Subtitle for home
  homeSubtitle = "I'm a"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = ["/css/style.css"]
  customJS  = ["/js/theme.js", "/js/text-animation.js"]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Show theme toggle in the navigation bar
  enableThemeToggle = true

[params.logo]
  logoText     = "Robin Dollé"
  logoHomeLink = "/"

# Social icons
#[[params.social]]
  #name = "email"
  #url  = "mailto:"

[[params.social]]
  name = "linkedin"
  url  = "https://linkedin.com/in/robindolle"

[[params.social]]
  name = "github"
  url  = "https://github.com/robindolle"

[[params.social]]
  name = "codepen"
  url  = "https://codepen.io/robindolle"

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/robindolle"

[languages]
  [languages.nl.params]
    homeSubtitle  = "Ik ben"
    weight        = 1
  [languages.en.params]
    homeSubtitle  = "I'm a"
    weight        = 2
  #[[languages.nl.menu.main]]
    #identifier    = "about"
    #name          = "Over"
    #url           = "/over"
  #[[languages.nl.menu.main]]
    #identifier    = "blog"
    #name          = "Blog"
    #url           = "/blog"

# Create a generic menu
#[menu]
  #[[menu.main]]
    #identifier = "about"
    #name       = "About"
    #url        = "/about"
  #[[menu.main]]
    #identifier = "blog"
    #name       = "Blog"
    #url        = "/blog"
